import { Bot } from 'lucide-react';

interface Props {
  /** ISO timestamp from when the content was generated. */
  generatedAt?: string;
  /** "case-study" | "briefing" | "social" | "intel-bundle" — drives the wording. */
  kind?: 'case-study' | 'briefing' | 'social' | 'intel-bundle' | 'generic';
  /** Override the variant for a darker background card. */
  variant?: 'inline' | 'banner';
  className?: string;
}

const KIND_COPY: Record<NonNullable<Props['kind']>, string> = {
  'case-study': 'Auto-generated case study',
  briefing: 'Auto-generated CTI briefing',
  social: 'Auto-generated social draft',
  'intel-bundle': 'Heuristic + LLM extraction',
  generic: 'Auto-generated',
};

/**
 * Surfaces machine-generated provenance on any page that renders LLM /
 * pipeline output. Reviewers should never mistake an auto-publish artefact
 * for hand-authored work; the inverse is also true — hand-authored
 * research without a badge reads as the analyst's own work.
 *
 * Banner variant = full-width rule below a hero (case studies, briefings).
 * Inline variant = small chip beside a section heading (social drafts).
 */
export function AutoGeneratedBadge({ generatedAt, kind = 'generic', variant = 'inline', className = '' }: Props) {
  const label = KIND_COPY[kind];
  const date = generatedAt
    ? new Date(generatedAt).toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' })
    : null;

  if (variant === 'banner') {
    return (
      <div
        role="note"
        aria-label={label}
        className={`flex items-start gap-2 rounded-md border border-amber-400/30 bg-amber-50 dark:bg-amber-950/20 px-3 py-2 ${className}`}
      >
        <Bot size={14} className="mt-0.5 text-amber-600 dark:text-amber-400 shrink-0" aria-hidden="true" />
        <p className="text-[12px] font-mono text-amber-800 dark:text-amber-200 leading-relaxed">
          <span className="font-semibold">{label}</span>
          {date && <span className="text-amber-700/80 dark:text-amber-300/80"> · {date}</span>}
          {kind === 'briefing' && (
            <span className="block text-[11px] text-amber-700/70 dark:text-amber-300/70 mt-0.5">
              Daily CTI summary produced by the platform from its own ingested feeds. Not a hand-authored writeup.
            </span>
          )}
          {kind === 'case-study' && (
            <span className="block text-[11px] text-amber-700/70 dark:text-amber-300/70 mt-0.5">
              Body written by the autonomous publish pipeline. Sources and IOCs reflect upstream data at generation
              time.
            </span>
          )}
        </p>
      </div>
    );
  }

  return (
    <span
      role="note"
      aria-label={label}
      className={`inline-flex items-center gap-1 rounded border border-amber-400/40 bg-amber-500/10 px-1.5 py-0.5 font-mono text-[10px] uppercase tracking-wider text-amber-700 dark:text-amber-300 ${className}`}
    >
      <Bot size={9} aria-hidden="true" /> auto-generated
      {date && <span className="opacity-70">· {date}</span>}
    </span>
  );
}
